<a href="https://colab.research.google.com/github/Andru-1987/data_science_95320/blob/master/02_clase/clase_02_intro_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

In [2]:
mi_variable = "soy un pato!"
print(mi_variable)

soy un pato!

In [3]:
mi_variable = "soy anderson"
print(mi_variable)

soy anderson

In [4]:
type(mi_variable)

str

In [6]:
mi_variable = [ 1,2,3,4,5 ]
print(mi_variable)

[1, 2, 3, 4, 5]

In [8]:
mi_variable[-1]

5

In [10]:
factura_uno = {
    "fecha_creacion": "01/01/202",
    "monto_facturado": 3000.00
}

print(factura_uno)

{'fecha_creacion': '01/01/202', 'monto_facturado': 3000.0}

In [11]:
from datetime import datetime

# 1. Definimos una lista de diccionarios con distintos formatos
facturacion = [
    {
        "id": 1,
        "fecha": "2026-05-11",           # Formato ISO (YYYY-MM-DD)
        "monto": 3000.00
    },
    {
        "id": 2,
        "fecha": "11/05/2026",           # Formato Latino (DD/MM/YYYY)
        "monto": 1500.50
    },
    {
        "id": 3,
        "fecha": "May 11, 2026",         # Formato Anglo/Texto
        "monto": 4200.00
    },
    {
        "id": 4,
        "fecha": datetime.now().strftime("%d-%m-%Y %H:%M"), # Con hora incluída
        "monto": 950.00
    }
]

In [14]:
facturacion[0]["monto"] + facturacion[1]["monto"] + facturacion[2]["monto"] + facturacion[3]["monto"]

9650.5

In [20]:
bolsa_de_plata = []
indice = 0

for factura in facturacion:
    bolsa_de_plata.append(factura["monto"])
    print(f"Esta bolsa esta creciendo -> {indice}")
    print(bolsa_de_plata)
    indice = indice + 1 # indice += 1

total = sum(bolsa_de_plata)
print(f"El gran total de esta recaudacion es:\t{total}" )
print(f"El promedio de esta recaudacion  es:\t{total / len(facturacion):.2f}" )

Esta bolsa esta creciendo -> 0
[3000.0]
Esta bolsa esta creciendo -> 1
[3000.0, 1500.5]
Esta bolsa esta creciendo -> 2
[3000.0, 1500.5, 4200.0]
Esta bolsa esta creciendo -> 3
[3000.0, 1500.5, 4200.0, 950.0]
El gran total de esta recaudacion es:	9650.5
El promedio de esta recaudacion  es:	2412.62

In [22]:
def suma_de_facturas(facturacion):
    bolsa_de_plata = [  factura["monto"]  for factura in facturacion  ]
    print(bolsa_de_plata)
    return sum(bolsa_de_plata)

In [23]:
suma_de_facturas(facturacion)

[3000.0, 1500.5, 4200.0, 950.0]

9650.5

In [21]:
# Ejemplo de acceso
for factura in facturacion:
    print(f"Factura #{factura['id']} - Fecha: {factura['fecha']} - Total: ${factura['monto']}")

Factura #1 - Fecha: 2026-05-11 - Total: $3000.0
Factura #2 - Fecha: 11/05/2026 - Total: $1500.5
Factura #3 - Fecha: May 11, 2026 - Total: $4200.0
Factura #4 - Fecha: 12-05-2026 00:25 - Total: $950.0

## Uso de datos reales

In [43]:
url_dataset = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSrBmOZLnrVcUxSAakGgU-hp24fPt0DDty8OyeBJdHUOip3fdOxSQfCg7Hedw2fSSvMphyYPu4J0NgK/pub?gid=0&single=true&output=csv"

In [44]:
import pandas as pd

In [45]:
dataset = pd.read_csv(url_dataset)

In [46]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
Subtotal,100.0,561.8147,289.328478,61.51,303.195,631.985,806.0125,996.27
Tax,100.0,56.1821,28.933243,6.15,30.320,63.200,80.6025,99.63
Total,100.0,617.9968,318.261721,67.66,333.515,695.185,886.6150,1095.90

In [47]:
dataset.dtypes

Invoice ID     object
Issue Date     object
Due Date       object
Paid Date      object
Subtotal      float64
Tax           float64
Total         float64
dtype: object

In [52]:
dataset

   Invoice ID  Issue Date    Due Date   Paid Date  Subtotal    Tax    Total
0     INV-001  2026-04-28  2026-05-28         NaN    580.11  58.01   638.12
1     INV-002  2026-05-03  2026-06-02  2026-06-05    668.28  66.83   735.11
2     INV-003  2026-05-02  2026-06-01  2026-05-25    996.27  99.63  1095.90
3     INV-004  2026-04-25  2026-05-25  2026-05-26    586.34  58.63   644.97
4     INV-005  2026-05-01  2026-05-31         NaN    701.30  70.13   771.43
..        ...         ...         ...         ...       ...    ...      ...
95    INV-096  2026-05-07  2026-06-06  2026-05-17    129.29  12.93   142.22
96    INV-097  2026-05-09  2026-06-08  2026-05-30    658.00  65.80   723.80
97    INV-098  2026-04-30  2026-05-30  2026-05-13    112.53  11.25   123.78
98    INV-099  2026-04-27  2026-05-27  2026-05-02    516.24  51.62   567.86
99    INV-100  2026-04-15  2026-05-15  2026-04-28    472.91  47.29   520.20

[100 rows x 7 columns]

In [48]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Invoice ID  100 non-null    object
 1   Issue Date  100 non-null    object
 2   Due Date    100 non-null    object
 3   Paid Date   76 non-null     object
 4   Subtotal    100 non-null    float64
 5   Tax         100 non-null    float64
 6   Total       100 non-null    float64
dtypes: float64(3), object(4)
memory usage: 5.6+ KB

In [54]:
dataset["Issue Date"] = pd.to_datetime( dataset["Issue Date"] )

In [56]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Invoice ID  100 non-null    object
 1   Issue Date  100 non-null    datetime64[ns]
 2   Due Date    100 non-null    object
 3   Paid Date   76 non-null     object
 4   Subtotal    100 non-null    float64
 5   Tax         100 non-null    float64
 6   Total       100 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 5.6+ KB

In [57]:
dataset[dataset["Issue Date"] == "2026-05-07" ]

   Invoice ID Issue Date    Due Date   Paid Date  Subtotal    Tax   Total
27    INV-028 2026-05-07  2026-06-06  2026-05-20    794.24  79.42  873.66
95    INV-096 2026-05-07  2026-06-06  2026-05-17    129.29  12.93  142.22

In [58]:
dataset[dataset["Issue Date"] > "2026-05-07" ]

   Invoice ID Issue Date    Due Date   Paid Date  Subtotal    Tax   Total
11    INV-012 2026-05-09  2026-06-08  2026-05-26    672.32  67.23  739.55
30    INV-031 2026-05-12  2026-06-11  2026-06-06    611.24  61.12  672.36
33    INV-034 2026-05-11  2026-06-10  2026-05-17    848.81  84.88  933.69
34    INV-035 2026-05-10  2026-06-09  2026-06-08    556.06  55.61  611.67
40    INV-041 2026-05-12  2026-06-11  2026-05-21    725.76  72.58  798.34
44    INV-045 2026-05-09  2026-06-08  2026-06-11     68.49   6.85   75.34
46    INV-047 2026-05-11  2026-06-10  2026-06-06    113.20  11.32  124.52
61    INV-062 2026-05-11  2026-06-10         NaN    638.32  63.83  702.15
63    INV-064 2026-05-09  2026-06-08  2026-05-17    879.73  87.97  967.70
69    INV-070 2026-05-12  2026-06-11  2026-06-10    689.77  68.98  758.75
71    INV-072 2026-05-12  2026-06-11         NaN    665.14  66.51  731.65
77    INV-078 2026-05-08  2026-06-07  2026-06-01    828.25  82.83  911.08
84    INV-085 2026-05-09  2026-06-08         NaN    112.82  11.28  124.10
86    INV-087 2026-05-12  2026-06-11  2026-06-08    165.73  16.57  182.30
96    INV-097 2026-05-09  2026-06-08  2026-05-30    658.00  65.80  723.80

In [61]:
dataset.sort_values(by="Total", ascending=False).iloc[0:10]

   Invoice ID Issue Date    Due Date   Paid Date  Subtotal    Tax    Total
2     INV-003 2026-05-02  2026-06-01  2026-05-25    996.27  99.63  1095.90
18    INV-019 2026-04-17  2026-05-17         NaN    995.29  99.53  1094.82
80    INV-081 2026-04-12  2026-05-12         NaN    992.18  99.22  1091.40
60    INV-061 2026-04-13  2026-05-13  2026-04-29    987.48  98.75  1086.23
85    INV-086 2026-04-15  2026-05-15  2026-04-28    986.48  98.65  1085.13
9     INV-010 2026-04-26  2026-05-26  2026-05-13    983.19  98.32  1081.51
70    INV-071 2026-05-05  2026-06-04  2026-05-14    981.35  98.14  1079.49
51    INV-052 2026-04-22  2026-05-22  2026-05-05    973.18  97.32  1070.50
76    INV-077 2026-04-20  2026-05-20  2026-05-08    972.88  97.29  1070.17
10    INV-011 2026-05-01  2026-05-31  2026-05-29    969.89  96.99  1066.88

In [64]:
cleaned_data = dataset.nlargest(10,columns=["Total"])

In [63]:
ruta_guardado = "/content/datasets_facturacion"

In [66]:
from pathlib import Path

In [67]:
cleaned_data.to_csv( Path(ruta_guardado) / "data_clean.csv")